name: health_sync_plugin
description: A Flutter plugin to sync health data from Health Connect-compatible apps.
version: 0.0.3
homepage: https://github.com/Lohitgb/health_sync_plugin.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"


dependencies:
  flutter:
    sdk: flutter

  # Plugin platform interface support
  plugin_platform_interface: ^2.0.2

  # Core dependencies with flexible but safe version ranges
  health: ">=13.0.1 <14.0.0"
  http: ">=1.4.0 <3.0.0"  # widened upper bound to allow future 2.x versions
  firebase_core: ">=3.14.0 <5.0.0"
  cloud_firestore: ">=5.6.9 <7.0.0"
  permission_handler: ">=11.3.1 <13.0.0"
  flutter_foreground_task: ">=9.1.0 <11.0.0"
  awesome_notifications: ">=0.10.1 <2.0.0"
  flutter_local_notifications: ">=19.2.1 <21.0.0"
  url_launcher: ">=6.3.1 <8.0.0"
  shared_preferences: ">=2.5.3 <4.0.0"
  intl: ">=0.20.2 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.noscura.patient
        pluginClass: HealthSyncPlugin
